blockchain: 
  type: fabric,
  config: /home/kingbayeed/hyperledger/caliper/benchmark/simple/fabricConfig.json
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  clients:
    type: local
    number: 5
  rounds:
  - label: query
    txNumber:
    - 15
    - 15
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    - type: fixed-rate
      opts:
        tps: 5
    callback: benchmark/simple/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
