---
test:
  clients:
    type: local
    number: 5
  rounds:
  - label: query
    txNumber:
    - 15
    - 15
    rateControl:
    - type: fixed-rate
      opts:
        tps: 5
    - type: fixed-rate
      opts:
        tps: 5
    callback: benchmark/marbles/query.js
monitor:
  type:
  - docker
  - process
  docker:
    name:
    - all
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
